### ISSUE TITLE
Issue #6 was closed but was not entirely fixed

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/react-modular-code#10]
Issue #6 has not been entirely fixed. Specifically, bullet point 1 which says

`Inside of the Named Exports section, directly above the Imports header, the code block dropped the function declaration prior to the values() function definition.`

is unfixed. The code block above the Import header (about 3/4 of the way down the page) still has a dropped function declaration before the `values()` function

**Comment by maxwellbenton** [comment]
HI @micahshute,

Thank you for catching this and providing feedback so quickly. We've updated the content to add `function` into the code snippet.

Thank you for contributing to a learn.co lesson!

**Comment by micahshute** [comment]
👍
