### ISSUE TITLE
MEME DOESN"T WORK

### ISSUE THREAD

**Issue by JHutsell** [learn-co-curriculum/react-modular-code#13]
The meme doesn't work.

**Comment by maxwellbenton** [comment]
Hi @JHutsell,

Thank you for spotting this and providing feedback. It looks like the site that image was hosted on is gone and the image isn't showing up on any other site. We've removed the GIF entirely to get rid of the broken link, which should resolve this issue. It wasn't a very funny meme anyway.

Thank you for contributing and helping to improve our lessons!
