### ISSUE TITLE
Reorganize these beginning lessons

### ISSUE THREAD

**Issue by nlewis84** [learn-co-curriculum/react-modular-code#20]
It really seems like this lesson would be better served right at the beginning of the React module. I understand that the intent with the previous labs may have been to "show all the cool things you can do with React", but Import and Export should have been explained before that. Please consider a reorg of these labs.

**Comment by graciemcguire** [comment]
Thanks for your feedback! We have just done a complete overhaul and reorganization of our React curriculum and appreciated your feedback. Happy coding!
