### ISSUE TITLE
Should mascot() here be  gryffMascot()?

### ISSUE THREAD

**Issue by wley3337** [learn-co-curriculum/react-modular-code#4]
import {function()} from
import {function()} from allows us to grab a specific function by name, and use that function within the body of a new module.

We're able to reference the function imported by its previously declared name, or rename it inside of our import statement.

// src/Hogwarts.js
import { colors } from './houses/Gryffindor.js'
import { mascot as gryffMascot } from './houses/Gryffindor.js'
 
colors()
// > 'Scarlet and Gold'
 
mascot()
// > 'The Lion'

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @wley3337.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
