### ISSUE TITLE
There's a typo when importing from HagridsHouse.js

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/react-modular-code#5]
Hello,

In the Export section, the code for importing the `whosehouse` function seems to be incorrect.

The source file is HagridsHouse.js,
BUT,

the in the Hogwarts.js file, it's being imported from:
import whoseHouse from **'./house.js'**

Right?
Mentioning it, as it could be confusing for someone just seeing import/export code for the first time.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kostanzhoglo.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
